# Use an official Python runtime as a parent image
FROM archlinux

# Install gcc and other dependencies
RUN pacman -Syu \
    base-devel\
    gcc \
    pkg-config \
    hdf5 \
    tree \
    python \
    python-pip \
    git --noconfirm \
    && rm -rf /var/lib/apt/lists/*

# Install gcc and other dependencies
RUN pacman -S --needed --noconfirm sudo && \
    useradd corvuvr -m && \
    passwd -d corvuvr && \
    printf 'corvuvr ALL=(ALL) ALL\n' | tee -a /etc/sudoers 

WORKDIR /home/corvuvr
COPY ./requirements.txt /home/corvuvr/requirements.txt
# Create user
USER corvuvr
# Copy the requirements file into the container
RUN python3 -m venv .venv && source .venv/bin/activate && pip install --no-cache-dir -r requirements.txt
WORKDIR /app