# Use an official Python runtime as a parent image
FROM archlinux:multilib-devel-20241215.0.289170

# Install gcc and other dependencies
RUN pacman -Syu \
    base-devel\
    gcc \
    pkg-config \
    hdf5 \
    tree \
    # python \
    python-pip \
    git --noconfirm \
    && rm -rf /var/lib/apt/lists/*

RUN pacman -Syy && pacman -Syu --noconfirm

# Install gcc and other dependencies
RUN pacman -S --needed --noconfirm sudo && \
    useradd corvuvr -m && \
    passwd -d corvuvr && \
    printf 'corvuvr ALL=(ALL) ALL\n' | tee -a /etc/sudoers 

WORKDIR /home/corvuvr
# Create user
USER corvuvr
RUN git clone https://aur.archlinux.org/python311.git && cd python311 && makepkg -si --noconfirm
# Copy the requirements file into the container
RUN curl -O https://bootstrap.pypa.io/get-pip.py && python3.11 get-pip.py
RUN python3.11 -m venv .venv 
COPY ./requirements.txt /home/corvuvr/requirements.txt
RUN source .venv/bin/activate && python3.11 -V && python3.11 -m pip install --no-cache-dir -r requirements.txt
WORKDIR /app